Task 1: 
 
  1. 
 
Write a function to compute 5/0 and use try/except to catch the exceptions. 

In [1]:
def division():
    try :
        a=5
        b = int(input()) #input 0 as b
        rem = a%b
    except Exception as e:
        print(e)

In [2]:
division()

0
integer division or modulo by zero


2. 
 
Implement a Python program to generate all sentences where subject is in ["Americans", "Indians"] and verb is in ["Play", "watch"] and the object is in ["Baseball","cricket"]. 
 
Hint: Subject,Verb and Object should be declared in the program as shown below. 
 
subjects=["Americans ","Indians"] verbs=["play","watch"] objects=["Baseball","Cricket"]

In [3]:
#Solution 1:
subjects = ["Americans ","Indians"] 
verbs = ["play","watch"] 
objects = ["Baseball","Cricket"] 
for i in subjects:
    for j in verbs:
        for k in objects:
            print([i+" "+j+" "+k])

['Americans  play Baseball']
['Americans  play Cricket']
['Americans  watch Baseball']
['Americans  watch Cricket']
['Indians play Baseball']
['Indians play Cricket']
['Indians watch Baseball']
['Indians watch Cricket']


In [4]:
#soluation 2:
subjects = ["Americans ","Indians"] 
verbs = ["play","watch"] 
objects = ["Baseball","Cricket"] 
list_comp = ([i+" "+j+" "+k] for i in subjects for j in verbs for k in objects)
for lm in list_comp:
    print(lm)

['Americans  play Baseball']
['Americans  play Cricket']
['Americans  watch Baseball']
['Americans  watch Cricket']
['Indians play Baseball']
['Indians play Cricket']
['Indians watch Baseball']
['Indians watch Cricket']


Task 2:  
 
 
1.  
 
Write a function so that the columns of the output matrix are powers of the input vector.  
The order of the powers is determined by the increasing boolean argument. Specifically, when              increasing is False, the i-th output column is the input vector raised element-wise to the power                of N - i - 1.  

In [5]:
#Solution 1:
    
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [6]:
#Solution 2:
def gen_vander_matrix(ipvector, n, increasing=False):
    
    if not increasing:
        op_matrix = np.array([x**(n-1-i) for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    elif increasing:
        op_matrix = np.array([x**i for x in ipvector for i in range(n)]).reshape(ipvector.size,n)
    
    return op_matrix

print("------------OUTPUT-------------\n")

inputvector = np.array([1,2,3,4,5])
no_col_opmat = 3
op_matx_dec_order = gen_vander_matrix(inputvector,no_col_opmat,False)
op_matx_inc_order = gen_vander_matrix(inputvector,no_col_opmat,True)

------------OUTPUT-------------



In [7]:
op_matx_dec_order

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1],
       [25,  5,  1]])

In [8]:
op_matx_inc_order

array([[ 1,  1,  1],
       [ 1,  2,  4],
       [ 1,  3,  9],
       [ 1,  4, 16],
       [ 1,  5, 25]])